name: onnxdrive CI

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==23.11.0
    - name: Check with black
      run: black --check .
  Test_Operator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install numpy==1.23.4
        python3 -m pip install scipy==1.9.3
        python3 setup.py install
        
    - name: test operator
      run: |
        cd test
        bash run.sh
      